#line 2 "src/parsing/asm_mipslex.c"

#line 4 "src/parsing/asm_mipslex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer asm_mips_create_buffer
#define yy_delete_buffer asm_mips_delete_buffer
#define yy_flex_debug asm_mips_flex_debug
#define yy_init_buffer asm_mips_init_buffer
#define yy_flush_buffer asm_mips_flush_buffer
#define yy_load_buffer_state asm_mips_load_buffer_state
#define yy_switch_to_buffer asm_mips_switch_to_buffer
#define yyin asm_mipsin
#define yyleng asm_mipsleng
#define yylex asm_mipslex
#define yylineno asm_mipslineno
#define yyout asm_mipsout
#define yyrestart asm_mipsrestart
#define yytext asm_mipstext
#define yywrap asm_mipswrap
#define yyalloc asm_mipsalloc
#define yyrealloc asm_mipsrealloc
#define yyfree asm_mipsfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE asm_mipsrestart(asm_mipsin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t asm_mipsleng;

extern FILE *asm_mipsin, *asm_mipsout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up asm_mipstext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up asm_mipstext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via asm_mipsrestart()), so that the user can continue scanning by
	 * just pointing asm_mipsin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when asm_mipstext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t asm_mipsleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow asm_mipswrap()'s to do buffer switches
 * instead of setting up a fresh asm_mipsin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void asm_mipsrestart (FILE *input_file  );
void asm_mips_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE asm_mips_create_buffer (FILE *file,int size  );
void asm_mips_delete_buffer (YY_BUFFER_STATE b  );
void asm_mips_flush_buffer (YY_BUFFER_STATE b  );
void asm_mipspush_buffer_state (YY_BUFFER_STATE new_buffer  );
void asm_mipspop_buffer_state (void );

static void asm_mipsensure_buffer_stack (void );
static void asm_mips_load_buffer_state (void );
static void asm_mips_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER asm_mips_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE asm_mips_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE asm_mips_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE asm_mips_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *asm_mipsalloc (yy_size_t  );
void *asm_mipsrealloc (void *,yy_size_t  );
void asm_mipsfree (void *  );

#define yy_new_buffer asm_mips_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        asm_mipsensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            asm_mips_create_buffer(asm_mipsin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        asm_mipsensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            asm_mips_create_buffer(asm_mipsin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *asm_mipsin = (FILE *) 0, *asm_mipsout = (FILE *) 0;

typedef int yy_state_type;

extern int asm_mipslineno;

int asm_mipslineno = 1;

extern char *asm_mipstext;
#define yytext_ptr asm_mipstext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up asm_mipstext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	asm_mipsleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 30
#define YY_END_OF_BUFFER 31
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[77] =
    {   0,
        0,    0,   31,   30,    3,    1,   30,   30,   26,   30,
        4,   30,   14,   15,   10,    8,   16,   13,   26,    9,
       20,   20,    2,   30,   30,   30,   21,   26,   26,    7,
        5,    6,    0,   23,    0,    0,   27,   26,   24,    0,
        0,    0,    0,   20,   29,   29,   29,   29,   29,    0,
       28,   11,   12,   26,   26,    0,    0,    0,   22,    0,
        0,   19,   18,   17,   17,    0,    0,    0,    0,    0,
        0,    0,    0,   25,    0,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
        1,   25,   26,   27,   28,   28,   28,   28,   28,   28,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
        1,   30,    1,   31,   32,    1,   33,   34,   28,   28,

       28,   33,   29,   29,   29,   29,   29,   29,   29,   35,
       36,   29,   29,   35,   29,   35,   29,   35,   29,   37,
       29,   29,    1,   38,    1,   39,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[40] =
    {   0,
        1,    1,    1,    2,    1,    3,    1,    1,    4,    1,
        5,    1,    1,    1,    1,    3,    1,    6,    6,    6,
        7,    1,    1,    1,    1,    4,    1,    8,    3,    4,
        1,    3,    9,    9,   10,    3,   10,    1,    1
    } ;

static yyconst flex_int16_t yy_base[88] =
    {   0,
        0,    0,  128,  293,  293,  293,   36,  124,   23,   49,
      293,   96,  293,  293,  293,  293,  293,  293,    0,  293,
       69,   11,  293,  121,   99,   91,  293,  101,    0,  293,
      293,  293,   42,  293,   34,  109,  293,    0,   37,   98,
       86,   86,   42,    0,   55,    0,   31,   45,  121,   91,
      293,  293,  293,    0,    0,   95,    0,    0,  293,   91,
        0,   73,    0,    0,    0,  141,  168,   82,  155,   71,
      114,    0,   48,  293,   42,  293,  202,  212,  220,  230,
      240,  249,  258,  263,  270,  275,  282
    } ;

static yyconst flex_int16_t yy_def[88] =
    {   0,
       76,    1,   76,   76,   76,   76,   77,   78,   79,   76,
       76,   80,   76,   76,   76,   76,   76,   76,   79,   76,
       76,   21,   76,   81,   76,   76,   76,   76,   28,   76,
       76,   76,   77,   76,   82,   78,   76,   79,   79,   10,
       10,   76,   83,   22,   22,   45,   45,   45,   76,   81,
       76,   76,   76,   28,   28,   77,   84,   85,   76,   76,
       86,   45,   48,   49,   49,   77,   77,   87,   76,   86,
       77,   67,   87,   76,   76,    0,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76
    } ;

static yyconst flex_int16_t yy_nxt[333] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   23,   24,   25,   26,    4,   27,   28,   29,    4,
       30,   29,   28,   28,   29,   29,   29,   31,   32,   34,
       39,   39,   39,   39,   45,   34,   46,   46,   62,   62,
       59,   56,   56,   56,   39,   39,   39,   39,   74,   60,
       60,   60,   63,   63,   63,   35,   40,   40,   40,   40,
       57,   35,   46,   46,   46,   46,   41,   40,   61,   59,
       40,   41,   41,   40,   40,   40,   44,   44,   44,   44,
       62,   62,   74,   51,   59,   58,   45,   46,   34,   59,

       46,   45,   47,   46,   48,   49,   38,   58,   69,   69,
       69,   37,   66,   66,   66,   53,   38,   34,   54,   54,
       54,   54,   52,   51,   35,   43,   37,   76,   55,   54,
       76,   76,   54,   55,   55,   54,   54,   54,   64,   64,
       64,   64,   76,   35,   34,   76,   76,   76,   65,   46,
       76,   76,   46,   65,   65,   46,   46,   46,   71,   71,
       71,   76,   76,   59,   76,   76,   76,   76,   76,   76,
       35,   34,   75,   75,   75,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   72,   72,   72,   72,   76,
       76,   76,   76,   76,   76,   72,   76,   35,   76,   76,

       72,   72,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   38,   76,   76,   38,   38,   38,   38,   38,
       42,   76,   42,   42,   42,   42,   42,   42,   42,   42,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       33,   76,   33,   76,   33,   76,   76,   33,   33,   42,
       76,   42,   76,   42,   76,   76,   42,   42,   67,   67,
       67,   67,   68,   76,   76,   76,   76,   68,   68,   68,
       70,   70,   70,   70,   73,   76,   73,   73,   73,   73,
       73,   73,    3,   76,   76,   76,   76,   76,   76,   76,

       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76
    } ;

static yyconst flex_int16_t yy_chk[333] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    7,
        9,    9,    9,    9,   22,   33,   22,   22,   47,   47,
       75,   35,   35,   35,   39,   39,   39,   39,   73,   43,
       43,   43,   48,   48,   48,    7,   10,   10,   10,   10,
       35,   33,   45,   45,   45,   45,   10,   10,   43,   70,
       10,   10,   10,   10,   10,   10,   21,   21,   21,   21,
       62,   62,   68,   50,   42,   41,   21,   21,   56,   60,

       21,   21,   21,   21,   21,   21,   28,   40,   60,   60,
       60,   36,   56,   56,   56,   26,   28,   71,   28,   28,
       28,   28,   25,   24,   56,   12,    8,    3,   28,   28,
        0,    0,   28,   28,   28,   28,   28,   28,   49,   49,
       49,   49,    0,   71,   66,    0,    0,    0,   49,   49,
        0,    0,   49,   49,   49,   49,   49,   49,   66,   66,
       66,    0,    0,   69,    0,    0,    0,    0,    0,    0,
       66,   67,   69,   69,   69,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   67,   67,   67,   67,    0,
        0,    0,    0,    0,    0,   67,    0,   67,    0,    0,

       67,   67,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   79,    0,    0,   79,   79,   79,   79,   79,
       80,    0,   80,   80,   80,   80,   80,   80,   80,   80,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       82,    0,   82,    0,   82,    0,    0,   82,   82,   83,
        0,   83,    0,   83,    0,    0,   83,   83,   84,   84,
       84,   84,   85,    0,    0,    0,    0,   85,   85,   85,
       86,   86,   86,   86,   87,    0,   87,   87,   87,   87,
       87,   87,   76,   76,   76,   76,   76,   76,   76,   76,

       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int asm_mips_flex_debug;
int asm_mips_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *asm_mipstext;
#line 1 "src/parsing/asm_mips.lex"
/* ###--------------------------------------------------------------### */
/* file		: asm_mips.lex						*/
/* date		: Jun 21 2010						*/
/* version	: v200							*/
/* author	: Pirouz Bazargan Sabet					*/
/* description	: assembler						*/
/* ###--------------------------------------------------------------### */
#line 11 "src/parsing/asm_mips.lex"
#include <stdlib.h>
#include <stdio.h>
#include "utl200.h"
#include "asm200.h"
//#include UTL_H
//#include ASM_H
#include "asm_mipsyac.h"

static int          search_token ();
static unsigned int search_valu  ();

#ifdef YY_DECL
#undef YY_DECL
#endif


#define YY_DECL int asm_mipslex (YYSTYPE *lval_pnt)
#define yylval (*lval_pnt)

//#define YY_NO_INPUT

// Try to fixes arguments asm_mipslex problem
//#define YY_DECL int asm_mipslex (lval_pnt) YYSTYPE *lval_pnt;
//#define yylval  (*lval_pnt)

//#define YY_DECL int asm_mipslex ();
//#define yylval  ()
#line 603 "src/parsing/asm_mipslex.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int asm_mipslex_destroy (void );

int asm_mipsget_debug (void );

void asm_mipsset_debug (int debug_flag  );

YY_EXTRA_TYPE asm_mipsget_extra (void );

void asm_mipsset_extra (YY_EXTRA_TYPE user_defined  );

FILE *asm_mipsget_in (void );

void asm_mipsset_in  (FILE * in_str  );

FILE *asm_mipsget_out (void );

void asm_mipsset_out  (FILE * out_str  );

yy_size_t asm_mipsget_leng (void );

char *asm_mipsget_text (void );

int asm_mipsget_lineno (void );

void asm_mipsset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int asm_mipswrap (void );
#else
extern int asm_mipswrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( asm_mipstext, asm_mipsleng, 1, asm_mipsout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( asm_mipsin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( asm_mipsin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, asm_mipsin))==0 && ferror(asm_mipsin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(asm_mipsin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int asm_mipslex (void);

#define YY_DECL int asm_mipslex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after asm_mipstext and asm_mipsleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 67 "src/parsing/asm_mips.lex"

#line 787 "src/parsing/asm_mipslex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! asm_mipsin )
			asm_mipsin = stdin;

		if ( ! asm_mipsout )
			asm_mipsout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			asm_mipsensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				asm_mips_create_buffer(asm_mipsin,YY_BUF_SIZE );
		}

		asm_mips_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of asm_mipstext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 77 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 293 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 68 "src/parsing/asm_mips.lex"
{ ASM_LINENO ++; return (CarriageReturn); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 69 "src/parsing/asm_mips.lex"
{                return (Colon         ); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 70 "src/parsing/asm_mips.lex"
{                                         }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 71 "src/parsing/asm_mips.lex"
{                return (Ampersand     ); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 72 "src/parsing/asm_mips.lex"
{                return (Bar           ); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 73 "src/parsing/asm_mips.lex"
{                return (Tilda         ); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 74 "src/parsing/asm_mips.lex"
{                return (Circomflex    ); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 75 "src/parsing/asm_mips.lex"
{                return (Plus          ); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 76 "src/parsing/asm_mips.lex"
{                return (Slash         ); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 77 "src/parsing/asm_mips.lex"
{                return (Star          ); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 78 "src/parsing/asm_mips.lex"
{                return (DoubleLess    ); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 79 "src/parsing/asm_mips.lex"
{                return (DoubleGreat   ); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 80 "src/parsing/asm_mips.lex"
{                return (Minus         ); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 81 "src/parsing/asm_mips.lex"
{                return (LeftParen     ); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 82 "src/parsing/asm_mips.lex"
{                return (RightParen    ); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 83 "src/parsing/asm_mips.lex"
{                return (Comma         ); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 84 "src/parsing/asm_mips.lex"
{
 		//yylval.uval = utl_HexToInt (asm_mipstext + 2, NULL);
		int rt ;
		rt = strtol(asm_mipstext+2,NULL,16) ;
 		yylval.uval = rt ;
		//printf("hex_value : %d",rt) ;
		return (Litteral);
			}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 92 "src/parsing/asm_mips.lex"
{
 		//yylval.uval = utl_OctToInt (asm_mipstext + 2, NULL);
		int rt ;
		rt = strtol(asm_mipstext+2,NULL,8) ;
 		yylval.uval = rt ;
		return (Litteral);
			}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 99 "src/parsing/asm_mips.lex"
{
 		yylval.uval = utl_BinToInt (asm_mipstext + 2, NULL);
		return (Litteral);
			}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 103 "src/parsing/asm_mips.lex"
{
 		if (sscanf (asm_mipstext, "%u", &yylval.uval) == 0)
		  yylval.uval = 0;
		return (Litteral);
			}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 108 "src/parsing/asm_mips.lex"
{
	return (Arobase) ;
}
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 112 "src/parsing/asm_mips.lex"
{
		char         *str    = NULL;
		char          c_val  ;

		str         = asm_mipstext + 1;
		c_val       = utl_CharToAscii (str, NULL);
		yylval.uval = (unsigned int) c_val;
		return (Litteral);
			}
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 121 "src/parsing/asm_mips.lex"
{
		char * str ;
		
		str = utl_SaveString (asm_mipstext);
	  	yylval.text = str;
		return (String);
		}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 129 "src/parsing/asm_mips.lex"
{
		yylval.uval = atoi (asm_mipstext + 1);
		return (ARegister);
			}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 135 "src/parsing/asm_mips.lex"
{
		char * str ;
		
		str = utl_SaveString (asm_mipstext);
	  	yylval.text = str;
		return (GCC_operator);
		}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 143 "src/parsing/asm_mips.lex"
{
		int           token;
		char         *ident;

		ident = utl_SaveString (asm_mipstext);
		token = search_token   (ident );

		if (token == 0)
		  {
		  yylval.text = ident;
		  return (Identifier);
		  }
		else
		  {
		  yylval.uval = search_valu (ident);
		  return (token);
		  }
		}
	YY_BREAK
case 27:
*yy_cp = (yy_hold_char); /* undo effects of setting up asm_mipstext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up asm_mipstext again */
YY_RULE_SETUP
#line 163 "src/parsing/asm_mips.lex"
{					}
	YY_BREAK
case 28:
*yy_cp = (yy_hold_char); /* undo effects of setting up asm_mipstext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up asm_mipstext again */
YY_RULE_SETUP
#line 164 "src/parsing/asm_mips.lex"
{					}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 167 "src/parsing/asm_mips.lex"
{
		char * str ;
		
		str = utl_SaveString (asm_mipstext);
	  	yylval.text = str;
		return (String2);
		}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 175 "src/parsing/asm_mips.lex"
ECHO;
	YY_BREAK
#line 1097 "src/parsing/asm_mipslex.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed asm_mipsin at a new source and called
			 * asm_mipslex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = asm_mipsin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( asm_mipswrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * asm_mipstext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of asm_mipslex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					asm_mipsrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			asm_mipsrestart(asm_mipsin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) asm_mipsrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 77 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 77 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 76);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up asm_mipstext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					asm_mipsrestart(asm_mipsin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( asm_mipswrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve asm_mipstext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void asm_mipsrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        asm_mipsensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            asm_mips_create_buffer(asm_mipsin,YY_BUF_SIZE );
	}

	asm_mips_init_buffer(YY_CURRENT_BUFFER,input_file );
	asm_mips_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void asm_mips_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		asm_mipspop_buffer_state();
	 *		asm_mipspush_buffer_state(new_buffer);
     */
	asm_mipsensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	asm_mips_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (asm_mipswrap()) processing, but the only time this flag
	 * is looked at is after asm_mipswrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void asm_mips_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	asm_mipsin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE asm_mips_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) asm_mipsalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in asm_mips_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) asm_mipsalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in asm_mips_create_buffer()" );

	b->yy_is_our_buffer = 1;

	asm_mips_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with asm_mips_create_buffer()
 * 
 */
    void asm_mips_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		asm_mipsfree((void *) b->yy_ch_buf  );

	asm_mipsfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a asm_mipsrestart() or at EOF.
 */
    static void asm_mips_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	asm_mips_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then asm_mips_init_buffer was _probably_
     * called from asm_mipsrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void asm_mips_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		asm_mips_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void asm_mipspush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	asm_mipsensure_buffer_stack();

	/* This block is copied from asm_mips_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from asm_mips_switch_to_buffer. */
	asm_mips_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void asm_mipspop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	asm_mips_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		asm_mips_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void asm_mipsensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)asm_mipsalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in asm_mipsensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)asm_mipsrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in asm_mipsensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE asm_mips_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) asm_mipsalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in asm_mips_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	asm_mips_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to asm_mipslex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       asm_mips_scan_bytes() instead.
 */
YY_BUFFER_STATE asm_mips_scan_string (yyconst char * yystr )
{
    
	return asm_mips_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to asm_mipslex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE asm_mips_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) asm_mipsalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in asm_mips_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = asm_mips_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in asm_mips_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up asm_mipstext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		asm_mipstext[asm_mipsleng] = (yy_hold_char); \
		(yy_c_buf_p) = asm_mipstext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		asm_mipsleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int asm_mipsget_lineno  (void)
{
        
    return asm_mipslineno;
}

/** Get the input stream.
 * 
 */
FILE *asm_mipsget_in  (void)
{
        return asm_mipsin;
}

/** Get the output stream.
 * 
 */
FILE *asm_mipsget_out  (void)
{
        return asm_mipsout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t asm_mipsget_leng  (void)
{
        return asm_mipsleng;
}

/** Get the current token.
 * 
 */

char *asm_mipsget_text  (void)
{
        return asm_mipstext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void asm_mipsset_lineno (int  line_number )
{
    
    asm_mipslineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see asm_mips_switch_to_buffer
 */
void asm_mipsset_in (FILE *  in_str )
{
        asm_mipsin = in_str ;
}

void asm_mipsset_out (FILE *  out_str )
{
        asm_mipsout = out_str ;
}

int asm_mipsget_debug  (void)
{
        return asm_mips_flex_debug;
}

void asm_mipsset_debug (int  bdebug )
{
        asm_mips_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from asm_mipslex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    asm_mipsin = stdin;
    asm_mipsout = stdout;
#else
    asm_mipsin = (FILE *) 0;
    asm_mipsout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * asm_mipslex_init()
     */
    return 0;
}

/* asm_mipslex_destroy is for both reentrant and non-reentrant scanners. */
int asm_mipslex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		asm_mips_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		asm_mipspop_buffer_state();
	}

	/* Destroy the stack itself. */
	asm_mipsfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * asm_mipslex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *asm_mipsalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *asm_mipsrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void asm_mipsfree (void * ptr )
{
	free( (char *) ptr );	/* see asm_mipsrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 175 "src/parsing/asm_mips.lex"



/* ###--------------------------------------------------------------### */
/* function	: asm_mipswrap						*/
/* description	: return 1						*/
/* called func.	: none							*/
/* ###--------------------------------------------------------------### */

int asm_mipswrap ()
  {
  return (1);
  }

/* ###--------------------------------------------------------------### */
/* function	: search_token						*/
/* description	: check if an identifier is a key-word or not		*/
/*									*/
/* called func.	: utl_CreateSimpleDic, utl_AddDicItem, utl_GetDicItem,	*/
/*		  utl_SaveString					*/
/* ###--------------------------------------------------------------### */

static int search_token (str)

char *str;

  {
  int                  val  = 0   ;
  static struct utdic *t_ht = NULL;

  if (t_ht == NULL)
    {
    t_ht = utl_CreateSimpleDic (UTL_DIC__BIG);

	/* ###------------------------------------------------------### */
	/*   key words							*/
	/* ###------------------------------------------------------### */

    utl_AddDicItem (t_ht, utl_SaveString ("$zero"     ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$at"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$v0"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$v1"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$a0"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$a1"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$a2"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$a3"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$t0"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$t1"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$t2"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$t3"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$t4"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$t5"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$t6"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$t7"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$s0"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$s1"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$s2"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$s3"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$s4"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$s5"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$s6"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$s7"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$t8"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$t9"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$k0"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$k1"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$gp"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$sp"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$s8"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("$ra"       ), IntegerRegister  );
	// ADD
    utl_AddDicItem (t_ht, utl_SaveString ("$fp"       ), IntegerRegister  );

    utl_AddDicItem (t_ht, utl_SaveString ("zero"      ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("at"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("v0"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("v1"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("a0"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("a1"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("a2"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("a3"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("t0"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("t1"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("t2"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("t3"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("t4"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("t5"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("t6"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("t7"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("s0"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("s1"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("s2"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("s3"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("s4"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("s5"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("s6"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("s7"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("t8"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("t9"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("k0"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("k1"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("gp"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("sp"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("s8"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("ra"        ), IntegerRegister  );

    utl_AddDicItem (t_ht, utl_SaveString ("r0"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r1"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r2"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r3"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r4"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r5"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r6"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r7"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r8"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r9"        ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r10"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r11"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r12"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r13"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r14"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r15"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r16"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r17"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r18"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r19"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r20"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r21"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r22"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r23"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r24"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r25"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r26"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r27"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r28"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r29"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r30"       ), IntegerRegister  );
    utl_AddDicItem (t_ht, utl_SaveString ("r31"       ), IntegerRegister  );

    utl_AddDicItem (t_ht, utl_SaveString ("badvaddr"  ), Cop0Register     );
    utl_AddDicItem (t_ht, utl_SaveString ("cause"     ), Cop0Register     );
    utl_AddDicItem (t_ht, utl_SaveString ("count"     ), Cop0Register     );
    utl_AddDicItem (t_ht, utl_SaveString ("epc"       ), Cop0Register     );
    utl_AddDicItem (t_ht, utl_SaveString ("prid"      ), Cop0Register     );
    utl_AddDicItem (t_ht, utl_SaveString ("status"    ), Cop0Register     );

    utl_AddDicItem (t_ht, utl_SaveString (".align"    ), _ALIGN_          );
    utl_AddDicItem (t_ht, utl_SaveString (".ascii"    ), _ASCII_          );
    utl_AddDicItem (t_ht, utl_SaveString (".asciiz"   ), _ASCIIZ_         );
    utl_AddDicItem (t_ht, utl_SaveString (".byte"     ), _BYTE_           );
    utl_AddDicItem (t_ht, utl_SaveString (".comm"     ), _COMM_           );
    utl_AddDicItem (t_ht, utl_SaveString (".end"      ), _END_            );
    utl_AddDicItem (t_ht, utl_SaveString (".ent"      ), _ENT_            );
    utl_AddDicItem (t_ht, utl_SaveString (".equ"      ), _EQU_            );
    utl_AddDicItem (t_ht, utl_SaveString (".extern"   ), _EXTERN_         );
    utl_AddDicItem (t_ht, utl_SaveString (".globl"    ), _GLOBAL_         );
    utl_AddDicItem (t_ht, utl_SaveString (".global"   ), _GLOBAL_         );
    utl_AddDicItem (t_ht, utl_SaveString (".lcomm"    ), _LCOMM_          );
    utl_AddDicItem (t_ht, utl_SaveString (".section"  ), _SECTION_        );
    utl_AddDicItem (t_ht, utl_SaveString (".set"      ), _SET_            );
    utl_AddDicItem (t_ht, utl_SaveString (".skip"     ), _SKIP_           );
    utl_AddDicItem (t_ht, utl_SaveString (".space"    ), _SPACE_          );
    utl_AddDicItem (t_ht, utl_SaveString (".word"     ), _WORD_           );

    utl_AddDicItem (t_ht, utl_SaveString ("reorder"   ), _REORDER_        );
    utl_AddDicItem (t_ht, utl_SaveString ("noreorder" ), _NOREORDER_      );

    utl_AddDicItem (t_ht, utl_SaveString ("b"         ), Macro_label      );
    utl_AddDicItem (t_ht, utl_SaveString ("beqz"      ), Macro_rs_label   );
    utl_AddDicItem (t_ht, utl_SaveString ("bnez"      ), Macro_rs_label   );
    utl_AddDicItem (t_ht, utl_SaveString ("la"        ), Macro_rd_label   );
    utl_AddDicItem (t_ht, utl_SaveString ("li"        ), Macro_rd_i32     );
    utl_AddDicItem (t_ht, utl_SaveString ("loadi"     ), Macro_rd_i32     );
    utl_AddDicItem (t_ht, utl_SaveString ("move"      ), Macro_rd_rs      );
    utl_AddDicItem (t_ht, utl_SaveString ("neg"       ), Macro_rd_rt      );
    utl_AddDicItem (t_ht, utl_SaveString ("negu"      ), Macro_rd_rt      );
    utl_AddDicItem (t_ht, utl_SaveString ("nop"       ), Macro_n          );

    utl_AddDicItem (t_ht, utl_SaveString ("add"       ), Codop_rd_rs_rt   );
    utl_AddDicItem (t_ht, utl_SaveString ("addi"      ), Codop_rd_rs_si16 );
    utl_AddDicItem (t_ht, utl_SaveString ("addu"      ), Codop_rd_rs_rt   );
    utl_AddDicItem (t_ht, utl_SaveString ("addiu"     ), Codop_rd_rs_si16 );
    utl_AddDicItem (t_ht, utl_SaveString ("and"       ), Codop_rd_rs_rt   );
    utl_AddDicItem (t_ht, utl_SaveString ("andi"      ), Codop_rd_rs_ui16 );

    utl_AddDicItem (t_ht, utl_SaveString ("beq"       ), Codop_rs_rt_label);
    utl_AddDicItem (t_ht, utl_SaveString ("bgez"      ), Codop_rs_label   );
    utl_AddDicItem (t_ht, utl_SaveString ("bgezal"    ), Codop_rs_label   );
    utl_AddDicItem (t_ht, utl_SaveString ("bgtz"      ), Codop_rs_label   );
    utl_AddDicItem (t_ht, utl_SaveString ("blez"      ), Codop_rs_label   );
    utl_AddDicItem (t_ht, utl_SaveString ("bltz"      ), Codop_rs_label   );
    utl_AddDicItem (t_ht, utl_SaveString ("bltzal"    ), Codop_rs_label   );
    utl_AddDicItem (t_ht, utl_SaveString ("bne"       ), Codop_rs_rt_label);
    utl_AddDicItem (t_ht, utl_SaveString ("break"     ), Codop_ui20       );

    utl_AddDicItem (t_ht, utl_SaveString ("j"         ), Codop_label      );
    utl_AddDicItem (t_ht, utl_SaveString ("jal"       ), Codop_label      );
    utl_AddDicItem (t_ht, utl_SaveString ("jalr"      ), Codop_od_rs      );
    utl_AddDicItem (t_ht, utl_SaveString ("jr"        ), Codop_rs         );

    utl_AddDicItem (t_ht, utl_SaveString ("lb"        ), Codop_rd_mem     );
    utl_AddDicItem (t_ht, utl_SaveString ("lbu"       ), Codop_rd_mem     );
    utl_AddDicItem (t_ht, utl_SaveString ("lh"        ), Codop_rd_mem     );
    utl_AddDicItem (t_ht, utl_SaveString ("lhu"       ), Codop_rd_mem     );
    utl_AddDicItem (t_ht, utl_SaveString ("lui"       ), Codop_rd_si16    );
    utl_AddDicItem (t_ht, utl_SaveString ("lw"        ), Codop_rd_mem     );
    utl_AddDicItem (t_ht, utl_SaveString ("lwl"       ), Codop_rd_mem     );
    utl_AddDicItem (t_ht, utl_SaveString ("lwr"       ), Codop_rd_mem     );

    utl_AddDicItem (t_ht, utl_SaveString ("mfc0"      ), Codop_rt_cop0r   );
    utl_AddDicItem (t_ht, utl_SaveString ("mfhi"      ), Codop_rd         );
    utl_AddDicItem (t_ht, utl_SaveString ("mflo"      ), Codop_rd         );
    utl_AddDicItem (t_ht, utl_SaveString ("mtc0"      ), Codop_rt_cop0r   );
    utl_AddDicItem (t_ht, utl_SaveString ("mthi"      ), Codop_rs         );
    utl_AddDicItem (t_ht, utl_SaveString ("mtlo"      ), Codop_rs         );
    utl_AddDicItem (t_ht, utl_SaveString ("mul"       ), Codop_rd_rs_rt   );
    utl_AddDicItem (t_ht, utl_SaveString ("mult"      ), Codop_rs_rt      );
    utl_AddDicItem (t_ht, utl_SaveString ("multu"     ), Codop_rs_rt      );

    utl_AddDicItem (t_ht, utl_SaveString ("nor"       ), Codop_rd_rs_rt   );

    utl_AddDicItem (t_ht, utl_SaveString ("or"        ), Codop_rd_rs_rt   );
    utl_AddDicItem (t_ht, utl_SaveString ("ori"       ), Codop_rd_rs_ui16 );

    utl_AddDicItem (t_ht, utl_SaveString ("sb"        ), Codop_rt_mem     );
    utl_AddDicItem (t_ht, utl_SaveString ("sh"        ), Codop_rt_mem     );
    utl_AddDicItem (t_ht, utl_SaveString ("sll"       ), Codop_rd_rt_sham );
    utl_AddDicItem (t_ht, utl_SaveString ("sllv"      ), Codop_rd_rt_rs   );
    utl_AddDicItem (t_ht, utl_SaveString ("slt"       ), Codop_rd_rs_rt   );
    utl_AddDicItem (t_ht, utl_SaveString ("slti"      ), Codop_rd_rs_si16 );
    utl_AddDicItem (t_ht, utl_SaveString ("sltiu"     ), Codop_rd_rs_si16 );
    utl_AddDicItem (t_ht, utl_SaveString ("sltu"      ), Codop_rd_rs_rt   );
    utl_AddDicItem (t_ht, utl_SaveString ("sra"       ), Codop_rd_rt_sham );
    utl_AddDicItem (t_ht, utl_SaveString ("srav"      ), Codop_rd_rt_rs   );
    utl_AddDicItem (t_ht, utl_SaveString ("srl"       ), Codop_rd_rt_sham );
    utl_AddDicItem (t_ht, utl_SaveString ("srlv"      ), Codop_rd_rt_rs   );
    utl_AddDicItem (t_ht, utl_SaveString ("sub"       ), Codop_rd_rs_rt   );
    utl_AddDicItem (t_ht, utl_SaveString ("subu"      ), Codop_rd_rs_rt   );
    utl_AddDicItem (t_ht, utl_SaveString ("sw"        ), Codop_rt_mem     );
    utl_AddDicItem (t_ht, utl_SaveString ("syscall"   ), Codop_n          );

    utl_AddDicItem (t_ht, utl_SaveString ("xor"       ), Codop_rd_rs_rt   );
    utl_AddDicItem (t_ht, utl_SaveString ("xori"      ), Codop_rd_rs_ui16 );

	/* ###------------------------------------------------------### */
	/*   architecture dependent key words				*/
	/* ###------------------------------------------------------### */

    //if (ASM_ARCHI == ASM_ARC__MIPS32)
    if (1)
      {
      utl_AddDicItem (t_ht, utl_SaveString ("clo"       ), Codop_rd_rs      );
      utl_AddDicItem (t_ht, utl_SaveString ("clz"       ), Codop_rd_rs      );
      utl_AddDicItem (t_ht, utl_SaveString ("div"       ), Codop_rs_rt      );
      utl_AddDicItem (t_ht, utl_SaveString ("divu"      ), Codop_rs_rt      );
      utl_AddDicItem (t_ht, utl_SaveString ("ebase"     ), Cop0Register     );
      utl_AddDicItem (t_ht, utl_SaveString ("eepc"      ), Cop0Register     );
      utl_AddDicItem (t_ht, utl_SaveString ("eret"      ), Codop_n          );
      utl_AddDicItem (t_ht, utl_SaveString ("ll"        ), Codop_rd_mem     );
      utl_AddDicItem (t_ht, utl_SaveString ("madd"      ), Codop_rs_rt      );
      utl_AddDicItem (t_ht, utl_SaveString ("maddu"     ), Codop_rs_rt      );
      utl_AddDicItem (t_ht, utl_SaveString ("mfc2"      ), Codop_rt_cop2r   );
      utl_AddDicItem (t_ht, utl_SaveString ("movn"      ), Codop_rd_rs_rt   );
      utl_AddDicItem (t_ht, utl_SaveString ("movz"      ), Codop_rd_rs_rt   );
      utl_AddDicItem (t_ht, utl_SaveString ("msub"      ), Codop_rs_rt      );
      utl_AddDicItem (t_ht, utl_SaveString ("msubu"     ), Codop_rs_rt      );
      utl_AddDicItem (t_ht, utl_SaveString ("mtc2"      ), Codop_rt_cop2r   );
      utl_AddDicItem (t_ht, utl_SaveString ("pref"      ), Codop_hint_mem   );
      utl_AddDicItem (t_ht, utl_SaveString ("sc"        ), Codop_rt_mem     );
      utl_AddDicItem (t_ht, utl_SaveString ("sync"      ), Codop_n          );
      utl_AddDicItem (t_ht, utl_SaveString ("tccontext" ), Cop0Register     );
      utl_AddDicItem (t_ht, utl_SaveString ("teq"       ), Codop_rs_rt      );
      utl_AddDicItem (t_ht, utl_SaveString ("teqi"      ), Codop_rs_si16    );
      utl_AddDicItem (t_ht, utl_SaveString ("tge"       ), Codop_rs_rt      );
      utl_AddDicItem (t_ht, utl_SaveString ("tgei"      ), Codop_rs_si16    );
      utl_AddDicItem (t_ht, utl_SaveString ("tgeiu"     ), Codop_rs_si16    );
      utl_AddDicItem (t_ht, utl_SaveString ("tgeu"      ), Codop_rs_rt      );
      utl_AddDicItem (t_ht, utl_SaveString ("tlt"       ), Codop_rs_rt      );
      utl_AddDicItem (t_ht, utl_SaveString ("tlti"      ), Codop_rs_si16    );
      utl_AddDicItem (t_ht, utl_SaveString ("tltiu"     ), Codop_rs_si16    );
      utl_AddDicItem (t_ht, utl_SaveString ("tltu"      ), Codop_rs_rt      );
      utl_AddDicItem (t_ht, utl_SaveString ("tne"       ), Codop_rs_rt      );
      utl_AddDicItem (t_ht, utl_SaveString ("tnei"      ), Codop_rs_si16    );
      utl_AddDicItem (t_ht, utl_SaveString ("wait"      ), Codop_n          );
      }

    //if (ASM_ARCHI == ASM_ARC__MIPS1 )
    if (1)
      {
      utl_AddDicItem (t_ht, utl_SaveString ("rfe"       ), Codop_n          );
      }

    }

  val = (int) utl_GetDicItem (t_ht, str);
  return (val);
  }

/* ###--------------------------------------------------------------### */
/* function	: search_valu						*/
/* description	: return the value corresponding to a token		*/
/*									*/
/* called func.	: utl_CreateSimpleDic, utl_AddDicItem, utl_GetDicItem,	*/
/*		  utl_SaveString					*/
/* ###--------------------------------------------------------------### */

static struct utdic *v_ht = NULL;

static unsigned int search_valu (str)

char *str;

  {
  unsigned int         val  = 0   ;
  //static struct utdic *v_ht = NULL;

  if (v_ht == NULL)
    {
    v_ht = utl_CreateSimpleDic (UTL_DIC__BIG);

	/* ###------------------------------------------------------### */
	/*   key words							*/
	/* ###------------------------------------------------------### */

    utl_AddDicItem (v_ht, utl_SaveString ("$zero"     ),                 0);
    utl_AddDicItem (v_ht, utl_SaveString ("$at"       ),                 1);
    utl_AddDicItem (v_ht, utl_SaveString ("$v0"       ),                 2);
    utl_AddDicItem (v_ht, utl_SaveString ("$v1"       ),                 3);
    utl_AddDicItem (v_ht, utl_SaveString ("$a0"       ),                 4);
    utl_AddDicItem (v_ht, utl_SaveString ("$a1"       ),                 5);
    utl_AddDicItem (v_ht, utl_SaveString ("$a2"       ),                 6);
    utl_AddDicItem (v_ht, utl_SaveString ("$a3"       ),                 7);
    utl_AddDicItem (v_ht, utl_SaveString ("$t0"       ),                 8);
    utl_AddDicItem (v_ht, utl_SaveString ("$t1"       ),                 9);
    utl_AddDicItem (v_ht, utl_SaveString ("$t2"       ),                10);
    utl_AddDicItem (v_ht, utl_SaveString ("$t3"       ),                11);
    utl_AddDicItem (v_ht, utl_SaveString ("$t4"       ),                12);
    utl_AddDicItem (v_ht, utl_SaveString ("$t5"       ),                13);
    utl_AddDicItem (v_ht, utl_SaveString ("$t6"       ),                14);
    utl_AddDicItem (v_ht, utl_SaveString ("$t7"       ),                15);
    utl_AddDicItem (v_ht, utl_SaveString ("$s0"       ),                16);
    utl_AddDicItem (v_ht, utl_SaveString ("$s1"       ),                17);
    utl_AddDicItem (v_ht, utl_SaveString ("$s2"       ),                18);
    utl_AddDicItem (v_ht, utl_SaveString ("$s3"       ),                19);
    utl_AddDicItem (v_ht, utl_SaveString ("$s4"       ),                20);
    utl_AddDicItem (v_ht, utl_SaveString ("$s5"       ),                21);
    utl_AddDicItem (v_ht, utl_SaveString ("$s6"       ),                22);
    utl_AddDicItem (v_ht, utl_SaveString ("$s7"       ),                23);
    utl_AddDicItem (v_ht, utl_SaveString ("$t8"       ),                24);
    utl_AddDicItem (v_ht, utl_SaveString ("$t9"       ),                25);
    utl_AddDicItem (v_ht, utl_SaveString ("$k0"       ),                26);
    utl_AddDicItem (v_ht, utl_SaveString ("$k1"       ),                27);
    utl_AddDicItem (v_ht, utl_SaveString ("$gp"       ),                28);
    utl_AddDicItem (v_ht, utl_SaveString ("$sp"       ),                29);
    utl_AddDicItem (v_ht, utl_SaveString ("$s8"       ),                30);
    utl_AddDicItem (v_ht, utl_SaveString ("$ra"       ),                31);
    // ADD 
	utl_AddDicItem (v_ht, utl_SaveString ("$fp"       ),                30);

    utl_AddDicItem (v_ht, utl_SaveString ("zero"      ),                 0);
    utl_AddDicItem (v_ht, utl_SaveString ("at"        ),                 1);
    utl_AddDicItem (v_ht, utl_SaveString ("v0"        ),                 2);
    utl_AddDicItem (v_ht, utl_SaveString ("v1"        ),                 3);
    utl_AddDicItem (v_ht, utl_SaveString ("a0"        ),                 4);
    utl_AddDicItem (v_ht, utl_SaveString ("a1"        ),                 5);
    utl_AddDicItem (v_ht, utl_SaveString ("a2"        ),                 6);
    utl_AddDicItem (v_ht, utl_SaveString ("a3"        ),                 7);
    utl_AddDicItem (v_ht, utl_SaveString ("t0"        ),                 8);
    utl_AddDicItem (v_ht, utl_SaveString ("t1"        ),                 9);
    utl_AddDicItem (v_ht, utl_SaveString ("t2"        ),                10);
    utl_AddDicItem (v_ht, utl_SaveString ("t3"        ),                11);
    utl_AddDicItem (v_ht, utl_SaveString ("t4"        ),                12);
    utl_AddDicItem (v_ht, utl_SaveString ("t5"        ),                13);
    utl_AddDicItem (v_ht, utl_SaveString ("t6"        ),                14);
    utl_AddDicItem (v_ht, utl_SaveString ("t7"        ),                15);
    utl_AddDicItem (v_ht, utl_SaveString ("s0"        ),                16);
    utl_AddDicItem (v_ht, utl_SaveString ("s1"        ),                17);
    utl_AddDicItem (v_ht, utl_SaveString ("s2"        ),                18);
    utl_AddDicItem (v_ht, utl_SaveString ("s3"        ),                19);
    utl_AddDicItem (v_ht, utl_SaveString ("s4"        ),                20);
    utl_AddDicItem (v_ht, utl_SaveString ("s5"        ),                21);
    utl_AddDicItem (v_ht, utl_SaveString ("s6"        ),                22);
    utl_AddDicItem (v_ht, utl_SaveString ("s7"        ),                23);
    utl_AddDicItem (v_ht, utl_SaveString ("t8"        ),                24);
    utl_AddDicItem (v_ht, utl_SaveString ("t9"        ),                25);
    utl_AddDicItem (v_ht, utl_SaveString ("k0"        ),                26);
    utl_AddDicItem (v_ht, utl_SaveString ("k1"        ),                27);
    utl_AddDicItem (v_ht, utl_SaveString ("gp"        ),                28);
    utl_AddDicItem (v_ht, utl_SaveString ("sp"        ),                29);
    utl_AddDicItem (v_ht, utl_SaveString ("s8"        ),                30);
    utl_AddDicItem (v_ht, utl_SaveString ("ra"        ),                31);

    utl_AddDicItem (v_ht, utl_SaveString ("r0"        ),                 0);
    utl_AddDicItem (v_ht, utl_SaveString ("r1"        ),                 1);
    utl_AddDicItem (v_ht, utl_SaveString ("r2"        ),                 2);
    utl_AddDicItem (v_ht, utl_SaveString ("r3"        ),                 3);
    utl_AddDicItem (v_ht, utl_SaveString ("r4"        ),                 4);
    utl_AddDicItem (v_ht, utl_SaveString ("r5"        ),                 5);
    utl_AddDicItem (v_ht, utl_SaveString ("r6"        ),                 6);
    utl_AddDicItem (v_ht, utl_SaveString ("r7"        ),                 7);
    utl_AddDicItem (v_ht, utl_SaveString ("r8"        ),                 8);
    utl_AddDicItem (v_ht, utl_SaveString ("r9"        ),                 9);
    utl_AddDicItem (v_ht, utl_SaveString ("r10"       ),                10);
    utl_AddDicItem (v_ht, utl_SaveString ("r11"       ),                11);
    utl_AddDicItem (v_ht, utl_SaveString ("r12"       ),                12);
    utl_AddDicItem (v_ht, utl_SaveString ("r13"       ),                13);
    utl_AddDicItem (v_ht, utl_SaveString ("r14"       ),                14);
    utl_AddDicItem (v_ht, utl_SaveString ("r15"       ),                15);
    utl_AddDicItem (v_ht, utl_SaveString ("r16"       ),                16);
    utl_AddDicItem (v_ht, utl_SaveString ("r17"       ),                17);
    utl_AddDicItem (v_ht, utl_SaveString ("r18"       ),                18);
    utl_AddDicItem (v_ht, utl_SaveString ("r19"       ),                19);
    utl_AddDicItem (v_ht, utl_SaveString ("r20"       ),                20);
    utl_AddDicItem (v_ht, utl_SaveString ("r21"       ),                21);
    utl_AddDicItem (v_ht, utl_SaveString ("r22"       ),                22);
    utl_AddDicItem (v_ht, utl_SaveString ("r23"       ),                23);
    utl_AddDicItem (v_ht, utl_SaveString ("r24"       ),                24);
    utl_AddDicItem (v_ht, utl_SaveString ("r25"       ),                25);
    utl_AddDicItem (v_ht, utl_SaveString ("r26"       ),                26);
    utl_AddDicItem (v_ht, utl_SaveString ("r27"       ),                27);
    utl_AddDicItem (v_ht, utl_SaveString ("r28"       ),                28);
    utl_AddDicItem (v_ht, utl_SaveString ("r29"       ),                29);
    utl_AddDicItem (v_ht, utl_SaveString ("r30"       ),                30);
    utl_AddDicItem (v_ht, utl_SaveString ("r31"       ),                31);

    utl_AddDicItem (v_ht, utl_SaveString ("badvaddr"  ), ASM_MPS__BADVADDR);
    utl_AddDicItem (v_ht, utl_SaveString ("cause"     ), ASM_MPS__CAUSE   );
    utl_AddDicItem (v_ht, utl_SaveString ("count"     ), ASM_MPS__COUNT   );
    utl_AddDicItem (v_ht, utl_SaveString ("epc"       ), ASM_MPS__EPC     );
    utl_AddDicItem (v_ht, utl_SaveString ("prid"      ), ASM_MPS__PRID    );
    utl_AddDicItem (v_ht, utl_SaveString ("status"    ), ASM_MPS__STATUS  );

    utl_AddDicItem (v_ht, utl_SaveString (".align"    ), _ALIGN_          );
    utl_AddDicItem (v_ht, utl_SaveString (".ascii"    ), _ASCII_          );
    utl_AddDicItem (v_ht, utl_SaveString (".asciiz"   ), _ASCIIZ_         );
    utl_AddDicItem (v_ht, utl_SaveString (".byte"     ), _BYTE_           );
    utl_AddDicItem (v_ht, utl_SaveString (".comm"     ), _COMM_           );
    utl_AddDicItem (v_ht, utl_SaveString (".end"      ), _END_            );
    utl_AddDicItem (v_ht, utl_SaveString (".ent"      ), _ENT_            );
    utl_AddDicItem (v_ht, utl_SaveString (".equ"      ), _EQU_            );
    utl_AddDicItem (v_ht, utl_SaveString (".extern"   ), _EXTERN_         );
    utl_AddDicItem (v_ht, utl_SaveString (".globl"    ), _GLOBAL_         );
    utl_AddDicItem (v_ht, utl_SaveString (".global"   ), _GLOBAL_         );
    utl_AddDicItem (v_ht, utl_SaveString (".lcomm"    ), _LCOMM_          );
    utl_AddDicItem (v_ht, utl_SaveString (".section"  ), _SECTION_        );
    utl_AddDicItem (v_ht, utl_SaveString (".set"      ), _SET_            );
    utl_AddDicItem (v_ht, utl_SaveString (".skip"     ), _SKIP_           );
    utl_AddDicItem (v_ht, utl_SaveString (".space"    ), _SPACE_          );
    utl_AddDicItem (v_ht, utl_SaveString (".word"     ), _WORD_           );

    utl_AddDicItem (v_ht, utl_SaveString ("reorder"   ), _REORDER_        );
    utl_AddDicItem (v_ht, utl_SaveString ("noreorder" ), _NOREORDER_      );

    utl_AddDicItem (v_ht, utl_SaveString ("b"         ), ASM_MPS__B       );
    utl_AddDicItem (v_ht, utl_SaveString ("beqz"      ), ASM_MPS__BEQZ    );
    utl_AddDicItem (v_ht, utl_SaveString ("bnez"      ), ASM_MPS__BNEZ    );
    utl_AddDicItem (v_ht, utl_SaveString ("la"        ), ASM_MPS__LI      );
    utl_AddDicItem (v_ht, utl_SaveString ("li"        ), ASM_MPS__LI      );
    utl_AddDicItem (v_ht, utl_SaveString ("loadi"     ), ASM_MPS__LI      );
    utl_AddDicItem (v_ht, utl_SaveString ("move"      ), ASM_MPS__MOVE    );
    utl_AddDicItem (v_ht, utl_SaveString ("neg"       ), ASM_MPS__NEG     );
    utl_AddDicItem (v_ht, utl_SaveString ("negu"      ), ASM_MPS__NEGU    );
    utl_AddDicItem (v_ht, utl_SaveString ("nop"       ), ASM_MPS__NOP     );

    utl_AddDicItem (v_ht, utl_SaveString ("add"       ), ASM_MPS__ADD     );
    utl_AddDicItem (v_ht, utl_SaveString ("addi"      ), ASM_MPS__ADDI    );
    utl_AddDicItem (v_ht, utl_SaveString ("addu"      ), ASM_MPS__ADDU    );
    utl_AddDicItem (v_ht, utl_SaveString ("addiu"     ), ASM_MPS__ADDIU   );
    utl_AddDicItem (v_ht, utl_SaveString ("and"       ), ASM_MPS__AND     );
    utl_AddDicItem (v_ht, utl_SaveString ("andi"      ), ASM_MPS__ANDI    );

    utl_AddDicItem (v_ht, utl_SaveString ("beq"       ), ASM_MPS__BEQ     );
    utl_AddDicItem (v_ht, utl_SaveString ("bgez"      ), ASM_MPS__BGEZ    );
    utl_AddDicItem (v_ht, utl_SaveString ("bgezal"    ), ASM_MPS__BGEZAL  );
    utl_AddDicItem (v_ht, utl_SaveString ("bgtz"      ), ASM_MPS__BGTZ    );
    utl_AddDicItem (v_ht, utl_SaveString ("blez"      ), ASM_MPS__BLEZ    );
    utl_AddDicItem (v_ht, utl_SaveString ("bltz"      ), ASM_MPS__BLTZ    );
    utl_AddDicItem (v_ht, utl_SaveString ("bltzal"    ), ASM_MPS__BLTZAL  );
    utl_AddDicItem (v_ht, utl_SaveString ("bne"       ), ASM_MPS__BNE     );
    utl_AddDicItem (v_ht, utl_SaveString ("break"     ), ASM_MPS__BREAK   );

    utl_AddDicItem (v_ht, utl_SaveString ("j"         ), ASM_MPS__J       );
    utl_AddDicItem (v_ht, utl_SaveString ("jal"       ), ASM_MPS__JAL     );
    utl_AddDicItem (v_ht, utl_SaveString ("jalr"      ), ASM_MPS__JALR    );
    utl_AddDicItem (v_ht, utl_SaveString ("jr"        ), ASM_MPS__JR      );

    utl_AddDicItem (v_ht, utl_SaveString ("lb"        ), ASM_MPS__LB      );
    utl_AddDicItem (v_ht, utl_SaveString ("lbu"       ), ASM_MPS__LBU     );
    utl_AddDicItem (v_ht, utl_SaveString ("lh"        ), ASM_MPS__LH      );
    utl_AddDicItem (v_ht, utl_SaveString ("lhu"       ), ASM_MPS__LHU     );
    utl_AddDicItem (v_ht, utl_SaveString ("lui"       ), ASM_MPS__LUI     );
    utl_AddDicItem (v_ht, utl_SaveString ("lw"        ), ASM_MPS__LW      );
    utl_AddDicItem (v_ht, utl_SaveString ("lwl"       ), ASM_MPS__LWL     );
    utl_AddDicItem (v_ht, utl_SaveString ("lwr"       ), ASM_MPS__LWR     );

    utl_AddDicItem (v_ht, utl_SaveString ("mfc0"      ), ASM_MPS__MFC0    );
    utl_AddDicItem (v_ht, utl_SaveString ("mfhi"      ), ASM_MPS__MFHI    );
    utl_AddDicItem (v_ht, utl_SaveString ("mflo"      ), ASM_MPS__MFLO    );
    utl_AddDicItem (v_ht, utl_SaveString ("mtc0"      ), ASM_MPS__MTC0    );
    utl_AddDicItem (v_ht, utl_SaveString ("mthi"      ), ASM_MPS__MTHI    );
    utl_AddDicItem (v_ht, utl_SaveString ("mtlo"      ), ASM_MPS__MTLO    );
    utl_AddDicItem (v_ht, utl_SaveString ("mul"       ), ASM_MPS__MUL     );
    utl_AddDicItem (v_ht, utl_SaveString ("mult"      ), ASM_MPS__MULT    );
    utl_AddDicItem (v_ht, utl_SaveString ("multu"     ), ASM_MPS__MULTU   );

    utl_AddDicItem (v_ht, utl_SaveString ("nor"       ), ASM_MPS__NOR     );

    utl_AddDicItem (v_ht, utl_SaveString ("or"        ), ASM_MPS__OR      );
    utl_AddDicItem (v_ht, utl_SaveString ("ori"       ), ASM_MPS__ORI     );

    utl_AddDicItem (v_ht, utl_SaveString ("sb"        ), ASM_MPS__SB      );
    utl_AddDicItem (v_ht, utl_SaveString ("sh"        ), ASM_MPS__SH      );
    utl_AddDicItem (v_ht, utl_SaveString ("sll"       ), ASM_MPS__SLL     );
    utl_AddDicItem (v_ht, utl_SaveString ("sllv"      ), ASM_MPS__SLLV    );
    utl_AddDicItem (v_ht, utl_SaveString ("slt"       ), ASM_MPS__SLT     );
    utl_AddDicItem (v_ht, utl_SaveString ("slti"      ), ASM_MPS__SLTI    );
    utl_AddDicItem (v_ht, utl_SaveString ("sltiu"     ), ASM_MPS__SLTIU   );
    utl_AddDicItem (v_ht, utl_SaveString ("sltu"      ), ASM_MPS__SLTU    );
    utl_AddDicItem (v_ht, utl_SaveString ("sra"       ), ASM_MPS__SRA     );
    utl_AddDicItem (v_ht, utl_SaveString ("srav"      ), ASM_MPS__SRAV    );
    utl_AddDicItem (v_ht, utl_SaveString ("srl"       ), ASM_MPS__SRL     );
    utl_AddDicItem (v_ht, utl_SaveString ("srlv"      ), ASM_MPS__SRLV    );
    utl_AddDicItem (v_ht, utl_SaveString ("sub"       ), ASM_MPS__SUB     );
    utl_AddDicItem (v_ht, utl_SaveString ("subu"      ), ASM_MPS__SUBU    );
    utl_AddDicItem (v_ht, utl_SaveString ("sw"        ), ASM_MPS__SW      );
    utl_AddDicItem (v_ht, utl_SaveString ("syscall"   ), ASM_MPS__SYSCALL );

    utl_AddDicItem (v_ht, utl_SaveString ("xor"       ), ASM_MPS__XOR     );
    utl_AddDicItem (v_ht, utl_SaveString ("xori"      ), ASM_MPS__XORI    );

	/* ###------------------------------------------------------### */
	/*   architecture dependent key words				*/
	/* ###------------------------------------------------------### */

    //if (ASM_ARCHI == ASM_ARC__MIPS32)
    if (1)
      {
      utl_AddDicItem (v_ht, utl_SaveString ("clo"       ), ASM_MPS__CLO      );
      utl_AddDicItem (v_ht, utl_SaveString ("clz"       ), ASM_MPS__CLZ      );
      utl_AddDicItem (v_ht, utl_SaveString ("div"       ), ASM_MPS__DIV      );
      utl_AddDicItem (v_ht, utl_SaveString ("divu"      ), ASM_MPS__DIVU     );
      utl_AddDicItem (v_ht, utl_SaveString ("ebase"     ), ASM_MPS__EBASE    );
      utl_AddDicItem (v_ht, utl_SaveString ("eepc"      ), ASM_MPS__EEPC     );
      utl_AddDicItem (v_ht, utl_SaveString ("eret"      ), ASM_MPS__ERET     );
      utl_AddDicItem (v_ht, utl_SaveString ("ll"        ), ASM_MPS__LL       );
      utl_AddDicItem (v_ht, utl_SaveString ("madd"      ), ASM_MPS__MADD     );
      utl_AddDicItem (v_ht, utl_SaveString ("maddu"     ), ASM_MPS__MADDU    );
      utl_AddDicItem (v_ht, utl_SaveString ("mfc2"      ), ASM_MPS__MFC2     );
      utl_AddDicItem (v_ht, utl_SaveString ("movn"      ), ASM_MPS__MOVN     );
      utl_AddDicItem (v_ht, utl_SaveString ("movz"      ), ASM_MPS__MOVZ     );
      utl_AddDicItem (v_ht, utl_SaveString ("msub"      ), ASM_MPS__MSUB     );
      utl_AddDicItem (v_ht, utl_SaveString ("msubu"     ), ASM_MPS__MSUBU    );
      utl_AddDicItem (v_ht, utl_SaveString ("mtc2"      ), ASM_MPS__MTC2     );
      utl_AddDicItem (v_ht, utl_SaveString ("pref"      ), ASM_MPS__PREF     );
      utl_AddDicItem (v_ht, utl_SaveString ("sc"        ), ASM_MPS__SC       );
      utl_AddDicItem (v_ht, utl_SaveString ("sync"      ), ASM_MPS__SYNC     );
      utl_AddDicItem (v_ht, utl_SaveString ("tccontext" ), ASM_MPS__TCCONTEXT);
      utl_AddDicItem (v_ht, utl_SaveString ("teq"       ), ASM_MPS__TEQ      );
      utl_AddDicItem (v_ht, utl_SaveString ("teqi"      ), ASM_MPS__TEQI     );
      utl_AddDicItem (v_ht, utl_SaveString ("tge"       ), ASM_MPS__TGE      );
      utl_AddDicItem (v_ht, utl_SaveString ("tgei"      ), ASM_MPS__TGEI     );
      utl_AddDicItem (v_ht, utl_SaveString ("tgeiu"     ), ASM_MPS__TGEIU    );
      utl_AddDicItem (v_ht, utl_SaveString ("tgeu"      ), ASM_MPS__TGEU     );
      utl_AddDicItem (v_ht, utl_SaveString ("tlt"       ), ASM_MPS__TLT      );
      utl_AddDicItem (v_ht, utl_SaveString ("tlti"      ), ASM_MPS__TLTI     );
      utl_AddDicItem (v_ht, utl_SaveString ("tltiu"     ), ASM_MPS__TLTIU    );
      utl_AddDicItem (v_ht, utl_SaveString ("tltu"      ), ASM_MPS__TLTU     );
      utl_AddDicItem (v_ht, utl_SaveString ("tne"       ), ASM_MPS__TNE      );
      utl_AddDicItem (v_ht, utl_SaveString ("tnei"      ), ASM_MPS__TNEI     );
      utl_AddDicItem (v_ht, utl_SaveString ("wait"      ), ASM_MPS__WAIT     );
      }

    //if (ASM_ARCHI == ASM_ARC__MIPS1 )
    if (1 )
      {
      utl_AddDicItem (v_ht, utl_SaveString ("rfe"       ), ASM_MPS__RFE      );
      }

    }

  val = (unsigned int) utl_GetDicItem (v_ht, str);
  return (val);
  }

